import { SelectItem } from 'primeng/api';   

export const COUNTRIES: SelectItem[] = [

{ label: 'Afganistán', value: 'Afganistán'},
{ label: 'Albania', value: 'Albania'},
{ label: 'Alemania', value: 'Alemania'},
{ label: 'Andorra', value: 'Andorra'},
{ label: 'Angola', value: 'Angola'},
{ label: 'Anguila', value: 'Anguila'},
{ label: 'Antártida', value: 'Antártida'},
{ label: 'Antigua y Barbuda', value: 'Antigua y Barbuda'},
{ label: 'Antillas holandesas', value: 'Antillas holandesas'},
{ label: 'Arabia Saudí', value: 'Arabia Saudí'},
{ label: 'Argelia', value: 'Argelia'},
{ label: 'Argentina',  value: 'Argentina'},
{ label: 'Armenia', value: 'Armenia'},
{ label: 'Aruba', value: 'Aruba'},
{ label: 'Australia', value: 'Australia'},
{ label: 'Austria', value: 'Austria'},
{ label: 'Azerbaiyán', value: 'Azerbaiyán'},
{ label: 'Bahamas', value: 'Bahamas'},
{ label: 'Bahrein', value: 'Bahrein'},
{ label: 'Bangladesh', value: 'Bangladesh'},
{ label: 'Barbados', value: 'Barbados'},
{ label: 'Bélgica', value: 'Bélgica'},
{ label: 'Belice', value: 'Belice'},
{ label: 'Benín', value: 'Benín'},
{ label: 'Bermudas', value: 'Bermudas'},
{ label: 'Bhután', value: 'Bhután'},
{ label: 'Bielorrusia', value: 'Bielorrusia'},
{ label: 'Birmania', value: 'Birmania'},
{ label: 'Bolivia', value: 'Bolivia'},
{ label: 'Bosnia y Herzegovina', value: 'Bosnia y Herzegovina'},
{ label: 'Botsuana', value: 'Botsuana'},
{ label: 'Brasil', value: 'Brasil'},
{ label: 'Brunei', value: 'Brunei'},
{ label: 'Bulgaria', value: 'Bulgaria'},
{ label: 'Burkina Faso', value: 'Burkina Faso'},
{ label: 'Burundi', value: 'Burundi'},
{ label: 'Cabo Verde', value: 'Cabo Verde'},
{ label: 'Camboya', value: 'Camboya'},
{ label: 'Camerún', value: 'Camerún'},
{ label: 'Canadá', value: 'Canadá'},
{ label: 'Chad',  value: 'Chad'},
{ label: 'Chile', value: 'Chile'},
{ label: 'China', value: 'China'},
{ label: 'Chipre', value: 'Chipre'},
{ label: 'Ciudad estado del Vaticano', value: 'Ciudad estado del Vaticano'},
{ label: 'Colombia', value: 'Colombia'},
{ label: 'Comores', value: 'Comores'},
{ label: 'Congo', value: 'Congo'},
{ label: 'Corea', value: 'Corea'},
{ label: 'Corea del Norte', value: 'Corea del Norte'},
{ label: 'Costa del Marfíl', value: 'Costa del Marfíl'},
{ label: 'Costa Rica', value: 'Costa Rica'},
{ label: 'Croacia', value: 'Croacia'},
{ label: 'Cuba', value: 'Cuba'},
{ label: 'Dinamarca', value: 'Dinamarca'},
{ label: 'Djibouri', value: 'Djibouri'},
{ label: 'Dominica', value: 'Dominica'},
{ label: 'Ecuador', value: 'Ecuador'},
{ label: 'Egipto', value: 'Egipto'},
{ label: 'El Salvador', value: 'El Salvador'},
{ label: 'Emiratos Arabes Unidos', value: 'Emiratos Arabes Unidos'},
{ label: 'Eritrea', value: 'Eritrea'},
{ label: 'Eslovaquia', value: 'Eslovaquia'},
{ label: 'Eslovenia', value: 'Eslovenia'},
{ label: 'España', value: 'España'},
{ label: 'Estados Unidos', value: 'Estados Unidos'},
{ label: 'Estonia', value: 'Estonia'},
{ label: 'Ex-República Yugoslava de Macedonia', value: 'Ex-República Yugoslava de Macedonia'},
{ label: 'Filipinas', value: 'Filipinas'},
{ label: 'Finlandia', value: 'Finlandia'},
{ label: 'Francia', value: 'Francia'},
{ label: 'Gabón', value: 'Gabón'},
{ label: 'Gambia', value: 'Gambia'},
{ label: 'Georgia', value: 'Georgia'},
{ label: 'Georgia del Sur y las islas Sandwich del Sur', value: 'Georgia del Sur y las islas Sandwich del Sur'},
{ label: 'Ghana', value: 'Ghana'},
{ label: 'Gibraltar', value: 'Gibraltar'},
{ label: 'Granada', value: 'Granada'},
{ label: 'Grecia', value: 'Grecia'},
{ label: 'Groenlandia', value: 'Groenlandia'},
{ label: 'Guadalupe', value: 'Guadalupe'},
{ label: 'Guam', value: 'Guam'},
{ label: 'Guatemala', value: 'Guatemala'},
{ label: 'Guayana', value: 'Guayana'},
{ label: 'Guayana francesa', value: 'Guayana francesa'},
{ label: 'Guinea', value: 'Guinea'},
{ label: 'Guinea Ecuatorial', value: 'Guinea Ecuatorial'},
{ label: 'Guinea-Bissau', value: 'Guinea-Bissau'},
{ label: 'Haití', value: 'Haití'},
{ label: 'Holanda', value: 'Holanda'},
{ label: 'Honduras', value: 'Honduras'},
{ label: 'Hong Kong R. A. E', value: 'Hong Kong R. A. E'},
{ label: 'Hungría', value: 'Hungría'},
{ label: 'India', value: 'India'},
{ label: 'Indonesia',  value: 'Indonesia'},
{ label: 'Irak', value: 'Irak'},
{ label: 'Irán', value: 'Irán'},
{ label: 'Irlanda', value: 'Irlanda'},
{ label: 'Isla Bouvet', value: 'Isla Bouvet'},
{ label: 'Isla Christmas', value: 'Isla Christmas'},
{ label: 'Isla Heard e Islas McDonald', value: 'Isla Heard e Islas McDonald'},
{ label: 'Islandia', value: 'Islandia'},
{ label: 'Islas Caimán', value: 'Islas Caimán'},
{ label: 'Islas Cook', value: 'Islas Cook'},
{ label: 'Islas de Cocos o Keeling', value: 'Islas de Cocos o Keeling'},
{ label: 'Islas Faroe', value: 'Islas Faroe'},
{ label: 'Islas Fiyi', value: 'Islas Fiyi'},
{ label: 'Islas Malvinas Islas Falkland', value: 'Islas Malvinas Islas Falkland'},
{ label: 'Islas Marianas del norte', value: 'Islas Marianas del norte'},
{ label: 'Islas Marshall', value: 'Islas Marshall'},
{ label: 'Islas menores de Estados Unidos', value: 'Islas menores de Estados Unidos'},
{ label: 'Islas Palau', value: 'Islas Palau'},
{ label: 'Islas Salomón', value: 'Islas Salomón'},
{ label: 'Islas Tokelau', value: 'Islas Tokelau'},
{ label: 'Islas Turks y Caicos', value: 'Islas Turks y Caicos'},
{ label: 'Islas Vírgenes EE.UU.', value: 'Islas Vírgenes EE.UU.'},
{ label: 'Islas Vírgenes Reino Unido', value: 'Islas Vírgenes Reino Unido'},
{ label: 'Israel', value: 'Israel'},
{ label: 'Italia', value: 'Italia'},
{ label: 'Jamaica', value: 'Jamaica'},
{ label: 'Japón', value: 'Japón'},
{ label: 'Jordania', value: 'Jordania'},
{ label: 'Kazajistán', value: 'Kazajistán'},
{ label: 'Kenia', value: 'Kenia'},
{ label: 'Kirguizistán', value: 'Kirguizistán'},
{ label: 'Kiribati', value: 'Kiribati'},
{ label: 'Kuwait', value: 'Kuwait'},
{ label: 'Laos', value: 'Laos'},
{ label: 'Lesoto', value: 'Lesoto'},
{ label: 'Letonia', value: 'Letonia'},
{ label: 'Líbano', value: 'Líbano'},
{ label: 'Liberia', value: 'Liberia'},
{ label: 'Libia', value: 'Libia'},
{ label: 'Liechtenstein', value: 'Liechtenstein'},
{ label: 'Lituania', value: 'Lituania'},
{ label: 'Luxemburgo', value: 'Luxemburgo'},
{ label: 'Macao R. A. E', value: 'Macao R. A. E'},
{ label: 'Madagascar', value: 'Madagascar'},
{ label: 'Malasia', value: 'Malasia'},
{ label: 'Malawi', value: 'Malawi'},
{ label: 'Maldivas', value: 'Maldivas'},
{ label: 'Malí', value: 'Malí'},
{ label: 'Malta', value: 'Malta'},
{ label: 'Marruecos', value: 'Marruecos'},
{ label: 'Martinica', value: 'Martinica'},
{ label: 'Mauricio', value: 'Mauricio'},
{ label: 'Mauritania', value: 'Mauritania'},
{ label: 'Mayotte', value: 'Mayotte'},
{ label: 'México', value: 'México'},
{ label: 'Micronesia', value: 'Micronesia'},
{ label: 'Moldavia', value: 'Moldavia'},
{ label: 'Mónaco', value: 'Mónaco'},
{ label: 'Mongolia', value: 'Mongolia'},
{ label: 'Montserrat', value: 'Montserrat'},
{ label: 'Mozambique', value: 'Mozambique'},
{ label: 'Namibia', value: 'Namibia'},
{ label: 'Nauru', value: 'Nauru'},
{ label: 'Nepal', value: 'Nepal'},
{ label: 'Nicaragua', value: 'Nicaragua'},
{ label: 'Níger', value: 'Níger'},
{ label: 'Nigeria', value: 'Nigeria'},
{ label: 'Niue', value: 'Niue'},
{ label: 'Norfolk', value: 'Norfolk'},
{ label: 'Noruega', value: 'Noruega'},
{ label: 'Nueva Caledonia', value: 'Nueva Caledonia'},
{ label: 'Nueva Zelanda', value: 'Nueva Zelanda'},
{ label: 'Omán', value: 'Omán'},
{ label: 'Panamá', value: 'Panamá'},
{ label: 'Papua Nueva Guinea', value: 'Papua Nueva Guinea'},
{ label: 'Paquistán', value: 'Paquistán'},
{ label: 'Paraguay', value: 'Paraguay'},
{ label: 'Perú', value: 'Perú'},
{ label: 'Pitcairn', value: 'Pitcairn'},
{ label: 'Polinesia francesa', value: 'Polinesia francesa'},
{ label: 'Polonia', value: 'Polonia'},
{ label: 'Portugal', value: 'Portugal'},
{ label: 'Puerto Rico', value: 'Puerto Rico'},
{ label: 'Qatar', value: 'Qatar'},
{ label: 'Reino Unido', value: 'Reino Unido'},
{ label: 'República Centroafricana', value: 'República Centroafricana'},
{ label: 'República Checa', value: 'República Checa'},
{ label: 'República de Sudáfrica', value: 'República de Sudáfrica'},
{ label: 'República Democrática del Congo Zaire', value: 'República Democrática del Congo Zaire'},
{ label: 'República Dominicana', value: 'República Dominicana'},
{ label: 'Reunión', value: 'Reunión'},
{ label: 'Ruanda', value: 'Ruanda'},
{ label: 'Rumania', value: 'Rumania'},
{ label: 'Rusia', value: 'Rusia'},
{ label: 'Samoa', value: 'Samoa'},
{ label: 'Samoa occidental', value: 'Samoa occidental'},
{ label: 'San Kitts y Nevis', value: 'San Kitts y Nevis'},
{ label: 'San Marino', value: 'San Marino'},
{ label: 'San Pierre y Miquelon', value: 'San Pierre y Miquelon'},
{ label: 'San Vicente e Islas Granadinas', value: 'San Vicente e Islas Granadinas'},
{ label: 'Santa Helena', value: 'Santa Helena'},
{ label: 'Santa Lucía', value: 'Santa Lucía'},
{ label: 'Santo Tomé y Príncipe', value: 'Santo Tomé y Príncipe'},
{ label: 'Senegal', value: 'Senegal'},
{ label: 'Serbia y Montenegro', value: 'Serbia y Montenegro'},
{ label: 'Sychelles', value: 'Seychelles'},
{ label: 'Sierra Leona', value: 'Sierra Leona'},
{ label: 'Singapur', value: 'Singapur'},
{ label: 'Siria', value: 'Siria'},
{ label: 'Somalia', value: 'Somalia'},
{ label: 'Sri Lanka', value: 'Sri Lanka'},
{ label: 'Suazilandia', value: 'Suazilandia'},
{ label: 'Sudán', value: 'Sudán'},
{ label: 'Suecia', value: 'Suecia'},
{ label: 'Suiza', value: 'Suiza'},
{ label: 'Surinam', value: 'Surinam'},
{ label: 'Svalbard', value: 'Svalbard'},
{ label: 'Tailandia', value: 'Tailandia'},
{ label: 'Taiwán', value: 'Taiwán'},
{ label: 'Tanzania', value: 'Tanzania'},
{ label: 'Tayikistán', value: 'Tayikistán'},
{ label: 'Territorios británicos del océano Indico', value: 'Territorios británicos del océano Indico'},
{ label: 'Territorios franceses del sur', value: 'Territorios franceses del sur'},
{ label: 'Timor Oriental', value: 'Timor Oriental'},
{ label: 'Togo', value: 'Togo'},
{ label: 'Tonga', value: 'Tonga'},
{ label: 'Trinidad y Tobago', value: 'Trinidad y Tobago'},
{ label: 'Túnez', value: 'Túnez'},
{ label: 'Turkmenistán', value: 'Turkmenistán'},
{ label: 'Turquía', value: 'Turquía'},
{ label: 'Tuvalu', value: 'Tuvalu'},
{ label: 'Ucrania', value: 'Ucrania'},
{ label: 'Uganda', value: 'Uganda'},
{ label: 'Uruguay', value: 'Uruguay'},
{ label: 'Uzbekistán', value: 'Uzbekistán'},
{ label: 'Vanuatu', value: 'Vanuatu'},
{ label: 'Venezuela', value: 'Venezuela'},
{ label: 'Vietnam', value: 'Vietnam'},
{ label: 'Wallis y Futuna', value: 'Wallis y Futuna'},
{ label: 'Yemen', value: 'Yemen'},
{ label: 'Zambia', value: 'Zambia'},
{ label: 'Zimbabue', value: 'Zimbabue'}
];